services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data/chroma_db:/app/chroma_db
      - ./data/repos:/app/data/repos
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GITHUB_PAT: ${GITHUB_PAT}
